# Generated by Django 3.1 on 2020-08-16 22:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employer_name', models.CharField(max_length=25)),
                ('employer_code', models.CharField(max_length=25)),
                ('member_count', models.IntegerField()),
                ('thumbnail', models.CharField(max_length=200)),
                ('register_date', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='MedicalLicense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_date', models.CharField(max_length=8)),
                ('final_date', models.CharField(max_length=8)),
                ('time', models.IntegerField()),
                ('member_code', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MemberData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('father', models.CharField(max_length=25)),
                ('mother', models.CharField(max_length=25)),
                ('hand', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_name', models.CharField(max_length=25)),
                ('member_code', models.IntegerField()),
                ('member_personal_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.memberdata')),
            ],
        ),
    ]
